---
- src: https://github.com/open-io/ansible-role-openio-gridinit.git
  version: "20.04"
  name: gridinit

- src: https://github.com/open-io/ansible-role-openio-repository.git
  version: "20.04"
  name: repo
...
